config/routes.rb
AppCrudImage::Application.routes.draw do
  root :to => "postings#index"
  resources :postings
  resources :users

end

app/models/posting.rb
class Posting < ActiveRecord::Base
  has_attached_file :photo, :styles => {:medium => "600x300>", :thumb => "100x200>"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/,
  :url => "/assets/postings/:id/:style/:basename.:extension",
  :path => "rails_root/public/assets/postings/:id/:style/:basename.:extension"
  validates_with AttachmentSizeValidator, :attributes => :photo, :less_than => 0.2.megabytes
end

app/models/user.rb
class User < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  def index
    @postings = Posting.all
  end
  def show
    @posting = Posting.find_by_id(params[:id])
  end

  def new
    @posting = Posting.new
  end
  def create
    @posting = Posting.new(params_posting)
    if @posting.save
      flash[:notice] = "Posting Saved"
      redirect_to action: 'index'
    else
      flash[:error] = "Data not Valid"
      render 'new'
    end
  end

  def edit
    @posting = Posting.find_by_id(params[:id])
  end
  def update
    @posting = Posting.find_by_id(params[:id])
    if @posting.update(params_posting)
      flash[:notice] = "Data Updated"
      redirect_to action: 'index'
    else
      flash[:error] = "data not valid"
      render 'edit'
    end
  end

    def destroy
      @posting = Posting.find_by_id(params[:id])
      if @posting.destroy
        flash[:notice] = "Data deleted"
        redirect_to action: 'index'
      else
        flash[:error] = "data not valid"
        redirect_to action: 'index'
      end
    end

  def params_posting
    params.require(:posting).permit(:photo, :title, :userid)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new(params_user)
    if @user.save
      flash[:notice] = "Succes add data"
      redirect_to action: 'index'
    else
      flash[:error] = "data not valid"
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end
  def update
    @user = User.find_by_id(params[:id])
    if @user.update(params_user)
      flash[:notice]= "Success update data"
      redirect_to action: 'index'
    else
      flash[:error] = "Data not valid"
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    if @user.destroy
      flash[:notice]= "Success update data"
      redirect_to action: 'index'
    else
      flash[:error] = "Data not valid"
      redirect_to action: 'index'
    end
  end

  def params_user
    params.require(:user).permit(:name,:username,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppCrudImage</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/postings/edit.html.erb
<h1>Postings#edit</h1>
<%= form_for @posting, html:{class:"form-horizontal",multipart: true} do |f| %>
  <filedset>
    <%= f.file_field :photo %>

    <div class="form-group">
      <%= f.label :title, class: "col-lg-1 control-label" %>
      <div class="col-lg-5">
        <%= f.text_area :title, cols: 20, rows: 10, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :userid, class: "col-lg-1 control-label" %>
      <div class="col-lg-5">
        <%= f.text_field :userid, class: "form-control" %>
      </div>
    </div>
    <%= f.submit :submit, class: "btn btn-primary" %>
  </fieldset>
<% end %>

app/views/postings/index.html.erb
<table class="table">
  <tr>
<% @n = 0  %>
<% @postings.each do |posting| %>
  <% @n +=1 %>
  <td>
  <table class="table table-bordered" style="width:150px" >
    <tr class="info" align="center">
      <td>
        <%= link_to image_tag(posting.photo.url(:thumb)), posting.photo.url(:medium), :popup =>['original image'] %>
      </td>
    </tr>
    <tr class="warning" align="center">
      <td><h2><%= posting.title %></h2></td>
    </tr>
    <tr>
      <td><%= link_to 'Edit', edit_posting_path(posting.id), class: 'btn btn-primary' %> | <%= link_to 'delete', posting_path(posting.id), method: 'DELETE', data:{confirm: 'Delete this posting ?'},class:'btn btn-danger' %></td>
    </tr>
  </table>
  </td>
  <% if @n % 8 == 0 %>
    </tr><tr>
  <% end %>

<% end %>
  </tr>
</table>
<%= link_to "New Posting", new_posting_path %>

app/views/postings/new.html.erb
<h1>Postings#new</h1>
<%= form_for @posting, html:{class:"form-horizontal", :multipart => true} do |f| %>
  <filedset>
    <%= f.file_field :photo %>
    <%= @posting.errors[:photo].first%>

    <div class="form-group">
      <%= f.label :title, class: "col-lg-1 control-label" %>
      <div class="col-lg-5">
        <%= f.text_field :title, cols: 20, rows: 10, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :userid, class: "col-lg-1 control-label" %>
      <div class="col-lg-5">
        <%= f.text_field :userid, class: "form-control" %>
      </div>
    </div>
    <%= f.submit :submit, class: "btn btn-primary" %>
  </fieldset>
<% end %>

app/views/postings/show.html.erb
<table class="table">
<tr align="center">
  <td>
    <%= image_tag(@posting.photo.url(:medium)) %>
  </td>
</tr>
</table>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<%= form_for @user, html: {class:"form-horizontal"} do |f| %>
<fieldset>
  <legend>Form User</legend>
  <div class="form-group">
    <%= f.label :username, class: "col-lg-1 control-label"  %>
    <div class="col-lg-3">
      <%= f.text_field :username, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-lg-1 control-label"  %>
    <div class="col-lg-3">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-lg-1 control-label"  %>
    <div class="col-lg-3">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <br/>
  <%= f.submit :submit, class:"btn btn-primary" %>
</fieldset>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<table class="table table-bordered" style = "width:500px">
  <tr class='info'>
    <thead>
      <th>User Nama</th>
      <th>Nama</th>
    </thead>
  </tr>
<% @users.each do |user| %>
  <tr class='warning'>
    <td><%= user.username %></td>
    <td><%= user.name %></td>
  </tr>
<% end %>
</table>
<%= link_to 'Create New', new_user_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<%= form_for @user, html:{class:"form-horizontal"} do |f| %>
<fieldset>
  <legend>Form User</legend>
  <div class="form-group">
    <%= f.label :username, class: "col-lg-1 control-label"  %>
    <div class="col-lg-3">
      <%= f.text_field :username, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-lg-1 control-label"  %>
    <div class="col-lg-3">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-lg-1 control-label"  %>
    <div class="col-lg-3">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <br/>
  <%= f.submit :submit, class:"btn btn-primary" %>
</fieldset>
<% end %>